spring.application.name=assignment-server

server.port=8080

storage.type=file

storage.file.path=./storage

spring.datasource.url=jdbc:h2:file:./data/factorialdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always

logging.level.root=INFO
logging.level.org.springframework=INFO